spring.application.name=hexagonal

spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=homestead
spring.datasource.password=secret

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway - ejecuta las migraciones solo una vez
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

